"""
exercise_library.py
-------------------
A curated library of exercises with metadata.
Used by the AI agent and future image generation features.
Each exercise entry describes the movement, muscle groups,
equipment needed, difficulty, and any injury contraindications.
"""

EXERCISES: list[dict] = [
    # ── Lower Body ──────────────────────────────────────────────────────────
    {
        "name": "Goblet Squat",
        "category": "strength",
        "muscle_groups": ["quads", "glutes", "core"],
        "avoid_if_pain": ["knee", "hip"],
        "equipment": "dumbbell or kettlebell",
        "difficulty": "beginner",
    },
    {
        "name": "Barbell Back Squat",
        "category": "strength",
        "muscle_groups": ["quads", "glutes", "hamstrings", "core"],
        "avoid_if_pain": ["knee", "hip", "lower back"],
        "equipment": "barbell",
        "difficulty": "intermediate",
    },
    {
        "name": "Romanian Deadlift",
        "category": "strength",
        "muscle_groups": ["hamstrings", "glutes", "lower back"],
        "avoid_if_pain": ["lower back", "hip"],
        "equipment": "barbell or dumbbells",
        "difficulty": "intermediate",
    },
    {
        "name": "Bulgarian Split Squat",
        "category": "strength",
        "muscle_groups": ["quads", "glutes", "hip flexors"],
        "avoid_if_pain": ["knee", "hip", "ankle"],
        "equipment": "dumbbells or bodyweight",
        "difficulty": "intermediate",
    },
    {
        "name": "Hip Thrust",
        "category": "strength",
        "muscle_groups": ["glutes", "hamstrings"],
        "avoid_if_pain": ["lower back", "hip"],
        "equipment": "barbell or bodyweight",
        "difficulty": "beginner",
    },
    {
        "name": "Walking Lunges",
        "category": "strength",
        "muscle_groups": ["quads", "glutes", "hamstrings"],
        "avoid_if_pain": ["knee", "hip", "ankle"],
        "equipment": "bodyweight or dumbbells",
        "difficulty": "beginner",
    },
    {
        "name": "Step Ups",
        "category": "strength",
        "muscle_groups": ["quads", "glutes"],
        "avoid_if_pain": ["knee", "ankle"],
        "equipment": "box or bench",
        "difficulty": "beginner",
    },
    {
        "name": "Leg Press",
        "category": "strength",
        "muscle_groups": ["quads", "glutes"],
        "avoid_if_pain": ["knee", "lower back"],
        "equipment": "machine",
        "difficulty": "beginner",
    },
    {
        "name": "Calf Raises",
        "category": "strength",
        "muscle_groups": ["calves"],
        "avoid_if_pain": ["achilles", "ankle", "foot"],
        "equipment": "bodyweight or machine",
        "difficulty": "beginner",
    },
    {
        "name": "Nordic Hamstring Curl",
        "category": "strength",
        "muscle_groups": ["hamstrings"],
        "avoid_if_pain": ["knee", "lower back"],
        "equipment": "bodyweight (partner or anchor)",
        "difficulty": "advanced",
    },
    # ── Upper Body Push ──────────────────────────────────────────────────────
    {
        "name": "Push Up",
        "category": "strength",
        "muscle_groups": ["chest", "triceps", "front deltoid", "core"],
        "avoid_if_pain": ["shoulder", "wrist", "elbow"],
        "equipment": "bodyweight",
        "difficulty": "beginner",
    },
    {
        "name": "Barbell Bench Press",
        "category": "strength",
        "muscle_groups": ["chest", "triceps", "front deltoid"],
        "avoid_if_pain": ["shoulder", "elbow", "wrist"],
        "equipment": "barbell",
        "difficulty": "intermediate",
    },
    {
        "name": "Dumbbell Shoulder Press",
        "category": "strength",
        "muscle_groups": ["deltoids", "triceps", "upper traps"],
        "avoid_if_pain": ["shoulder", "neck", "elbow"],
        "equipment": "dumbbells",
        "difficulty": "beginner",
    },
    {
        "name": "Incline Dumbbell Press",
        "category": "strength",
        "muscle_groups": ["upper chest", "front deltoid", "triceps"],
        "avoid_if_pain": ["shoulder", "elbow"],
        "equipment": "dumbbells",
        "difficulty": "beginner",
    },
    {
        "name": "Tricep Dips",
        "category": "strength",
        "muscle_groups": ["triceps", "chest", "front deltoid"],
        "avoid_if_pain": ["shoulder", "elbow", "wrist"],
        "equipment": "parallel bars or bench",
        "difficulty": "intermediate",
    },
    {
        "name": "Lateral Raises",
        "category": "strength",
        "muscle_groups": ["lateral deltoid"],
        "avoid_if_pain": ["shoulder"],
        "equipment": "dumbbells",
        "difficulty": "beginner",
    },
    # ── Upper Body Pull ──────────────────────────────────────────────────────
    {
        "name": "Pull Up",
        "category": "strength",
        "muscle_groups": ["lats", "biceps", "rear deltoid"],
        "avoid_if_pain": ["shoulder", "elbow", "wrist"],
        "equipment": "pull-up bar",
        "difficulty": "intermediate",
    },
    {
        "name": "Lat Pulldown",
        "category": "strength",
        "muscle_groups": ["lats", "biceps"],
        "avoid_if_pain": ["shoulder", "elbow"],
        "equipment": "cable machine",
        "difficulty": "beginner",
    },
    {
        "name": "Seated Cable Row",
        "category": "strength",
        "muscle_groups": ["lats", "mid traps", "rhomboids", "biceps"],
        "avoid_if_pain": ["lower back", "shoulder", "elbow"],
        "equipment": "cable machine",
        "difficulty": "beginner",
    },
    {
        "name": "Dumbbell Row",
        "category": "strength",
        "muscle_groups": ["lats", "rhomboids", "biceps"],
        "avoid_if_pain": ["lower back", "shoulder", "elbow", "wrist"],
        "equipment": "dumbbell",
        "difficulty": "beginner",
    },
    {
        "name": "Face Pull",
        "category": "strength",
        "muscle_groups": ["rear deltoid", "rotator cuff", "upper traps"],
        "avoid_if_pain": ["shoulder", "elbow"],
        "equipment": "cable machine",
        "difficulty": "beginner",
    },
    # ── Core ─────────────────────────────────────────────────────────────────
    {
        "name": "Plank",
        "category": "core",
        "muscle_groups": ["core", "transverse abdominis"],
        "avoid_if_pain": ["lower back", "wrist", "shoulder"],
        "equipment": "bodyweight",
        "difficulty": "beginner",
    },
    {
        "name": "Dead Bug",
        "category": "core",
        "muscle_groups": ["core", "hip flexors"],
        "avoid_if_pain": ["lower back"],
        "equipment": "bodyweight",
        "difficulty": "beginner",
    },
    {
        "name": "Pallof Press",
        "category": "core",
        "muscle_groups": ["core", "obliques"],
        "avoid_if_pain": ["shoulder", "lower back"],
        "equipment": "cable machine or band",
        "difficulty": "beginner",
    },
    {
        "name": "Ab Wheel Rollout",
        "category": "core",
        "muscle_groups": ["core", "lats"],
        "avoid_if_pain": ["lower back", "shoulder", "wrist"],
        "equipment": "ab wheel",
        "difficulty": "advanced",
    },
    # ── Hinge / Posterior Chain ───────────────────────────────────────────────
    {
        "name": "Conventional Deadlift",
        "category": "strength",
        "muscle_groups": ["hamstrings", "glutes", "lower back", "lats", "traps"],
        "avoid_if_pain": ["lower back", "hip", "knee"],
        "equipment": "barbell",
        "difficulty": "intermediate",
    },
    {
        "name": "Kettlebell Swing",
        "category": "power",
        "muscle_groups": ["glutes", "hamstrings", "core"],
        "avoid_if_pain": ["lower back", "shoulder", "wrist"],
        "equipment": "kettlebell",
        "difficulty": "intermediate",
    },
    {
        "name": "Good Morning",
        "category": "strength",
        "muscle_groups": ["hamstrings", "glutes", "lower back"],
        "avoid_if_pain": ["lower back"],
        "equipment": "barbell or bodyweight",
        "difficulty": "intermediate",
    },
    # ── Power / Plyometrics ──────────────────────────────────────────────────
    {
        "name": "Box Jump",
        "category": "power",
        "muscle_groups": ["quads", "glutes", "calves"],
        "avoid_if_pain": ["knee", "ankle", "hip"],
        "equipment": "plyo box",
        "difficulty": "intermediate",
    },
    {
        "name": "Broad Jump",
        "category": "power",
        "muscle_groups": ["quads", "glutes", "hamstrings"],
        "avoid_if_pain": ["knee", "ankle", "hip"],
        "equipment": "bodyweight",
        "difficulty": "intermediate",
    },
    {
        "name": "Medicine Ball Slam",
        "category": "power",
        "muscle_groups": ["core", "lats", "glutes"],
        "avoid_if_pain": ["shoulder", "lower back"],
        "equipment": "medicine ball",
        "difficulty": "beginner",
    },
    # ── Mobility / Rehab ─────────────────────────────────────────────────────
    {
        "name": "World's Greatest Stretch",
        "category": "mobility",
        "muscle_groups": ["hip flexors", "thoracic spine", "hamstrings"],
        "avoid_if_pain": [],
        "equipment": "bodyweight",
        "difficulty": "beginner",
    },
    {
        "name": "90/90 Hip Stretch",
        "category": "mobility",
        "muscle_groups": ["hip rotators", "glutes"],
        "avoid_if_pain": ["knee"],
        "equipment": "bodyweight",
        "difficulty": "beginner",
    },
    {
        "name": "Cat-Cow",
        "category": "mobility",
        "muscle_groups": ["spine", "core"],
        "avoid_if_pain": [],
        "equipment": "bodyweight",
        "difficulty": "beginner",
    },
    {
        "name": "Band Pull-Apart",
        "category": "mobility",
        "muscle_groups": ["rear deltoid", "rotator cuff", "rhomboids"],
        "avoid_if_pain": ["shoulder", "elbow"],
        "equipment": "resistance band",
        "difficulty": "beginner",
    },
    {
        "name": "Ankle Circles",
        "category": "mobility",
        "muscle_groups": ["ankle stabilisers"],
        "avoid_if_pain": [],
        "equipment": "bodyweight",
        "difficulty": "beginner",
    },
    # ── Conditioning / Cardio ────────────────────────────────────────────────
    {
        "name": "Rowing Machine",
        "category": "cardio",
        "muscle_groups": ["full body"],
        "avoid_if_pain": ["lower back", "shoulder"],
        "equipment": "rowing ergometer",
        "difficulty": "beginner",
    },
    {
        "name": "Assault Bike",
        "category": "cardio",
        "muscle_groups": ["full body"],
        "avoid_if_pain": ["shoulder"],
        "equipment": "assault bike",
        "difficulty": "beginner",
    },
    {
        "name": "Jump Rope",
        "category": "cardio",
        "muscle_groups": ["calves", "shoulders", "core"],
        "avoid_if_pain": ["ankle", "knee", "achilles", "shoulder", "wrist"],
        "equipment": "jump rope",
        "difficulty": "beginner",
    },
    {
        "name": "Sled Push",
        "category": "conditioning",
        "muscle_groups": ["quads", "glutes", "core"],
        "avoid_if_pain": ["knee", "hip", "lower back"],
        "equipment": "sled",
        "difficulty": "intermediate",
    },
    {
        "name": "Farmer's Carry",
        "category": "conditioning",
        "muscle_groups": ["traps", "core", "grip", "glutes"],
        "avoid_if_pain": ["shoulder", "wrist", "lower back"],
        "equipment": "dumbbells or kettlebells",
        "difficulty": "beginner",
    },
]
